experiment_name: ${exp_name}_${graph_creation.graphs.max_edge_size}_${graph_creation.subgraphs.d_to_centroid}

mlflow:
  databricks_base_name: ???
  tracking_uri: databricks
  experiment_name: ${.databricks_base_name}/${..experiment_name}

training_params:
  features_list:
    - area
    - major_axis_length
    - minor_axis_length
    - eccentricity
    - circularity
    - pdl1
    - cd8
    - pd1
  trainer_params:
    accumulate_grad_batches: 1
    early_stopping_patience: 3
    max_epochs: 2
    val_split: 0.15
    val: False
  data_module_params:
    batch_size: 32
  model_params:
    hid_units: 8
    dropout: 0
    n_layers: 2
  optimization_params:
    l2_coeff: 5e-4
    lr_scheduler_gamma: 0.75
    lr_scheduler_step_size: 10
    lr: 1e-3
